project:
  type: website
  output-dir: docs

website:
  title: "Dog Capital"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - text: Programs
        menu:
          - href: programs/es-core.qmd
            text: ES Core
          - href: programs/spy-core.qmd
            text: SPY Core

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
