project:
  type: website
  output-dir: docs
  resources:
    - "programs/es-core/**"
    - "programs/spy-core/**"

website:
  title: "Dog Capital"
  navbar: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
